### ISSUE TITLE
afFieldInput

### ISSUE THREAD

**Issue by rogueturnip** [yogiben/meteor-autoform-map#14]
Hi!

I'm trying to use the form with a schema defined in Collections2 and most of the afFieldInput items don't seem to be working for me.  Here is what I've put into my collection:
    startLocation: {
        type: String,
        autoform: {
            afFieldInput: {
                type: 'map',
                mapType: 'terrain',
                zoom: '8',
                searchBox: true,
                width: '50%',
                defaultLat: '46.073',
                defaultLng: '-100.546',
                geolocation: true,
            }
        }
    }

The width, searchBox, and geolocation seem to work but I'm not getting the proper zoom or centering based on Lat Lng.,

An example on how to use the googleMaps option to specify the options would be great too.

Thanks for a great tool!

**Comment by yogiben** [comment]
There are some new examples in the Readme. I hope they help.

**Comment by rogueturnip** [comment]
THanks, this helps a bit, but I can't get it to take the defaultlat or defaultlng and the map zoom isn't working when I set it up.

Also, on an autoform update will it use the lat and lng stored to create the map in the form?

**Comment by mpowaga** [comment]
@rogueturnip Seems to be solved. Closing. Feel free to open if it still doesn't work.
