### ISSUE TITLE
Map options not taking effect

### ISSUE THREAD

**Issue by mikeconstable** [yogiben/meteor-autoform-map#15]
Hi,

I've been using a basic autoform-map successfully (thanks!), however I can't seem to get any changes from adding map options. Example below is ensuring searchBox is turn off, but the search box is always rendered (I know it is supposed to be off by default):

{{#autoForm id="viewUserProfile" schema="Schema.User" doc=currentUser type="readonly"}}
   {{> afQuickField name="profile.location" width="125px" height="75px" searchBox=false zoom=4 label=false}}
{{/autoForm}}

![screen shot 2015-01-21 at 09 55 51](https://cloud.githubusercontent.com/assets/7543482/5834286/bbc1b844-a153-11e4-9e90-99107f053f2f.png)

Also not had luck trying to include other API options such as 'disableDefaultUI'. Can you provide a simple example or are they not possible as it stands?

**Comment by yogiben** [comment]
Try adding them in the schema (like the readme examples).

Right now, you cannot pass any google maps options directly. This would be good.

**Comment by mikeconstable** [comment]
Thanks for your response, however, just tried adding them to the schema but it's not changing the map, other than for the options listed. Cannot get the googleMap options to take. I'll investigate a direct google map API instance and read coordinates from the DB instead. I only need to format a read-only map.

**Comment by rogueturnip** [comment]
I'm seeing the same issue.  In addition if you create an update form the map is greyed out.

**Comment by mpowaga** [comment]
Google Maps specific options can be set using `rendered` callback.

**Comment by mikeconstable** [comment]
Thanks. Is there an example anywhere? I've tried setting a callback for rendered with some options but it had no effect - which means I'm likely doing it wrong.

**Comment by mpowaga** [comment]
It's mentioned in the readme. Here's example:

```
Schemas.Locations = new SimpleSchema({
  title: {
    type: String
  },

  place: {
    type: String,
    autoform: {
      type: 'map',
      afFieldInput: {
        rendered: function (map) {
          // Add custom options using 'map'
        }
      }
    }
  }
});
```
