### ISSUE TITLE
Cannot read property 'zoom' of undefined

### ISSUE THREAD

**Issue by filipenevola** [yogiben/meteor-autoform-map#18]
Hi guys, I'm getting this error on browser console:

yogiben_autoform-map.js:179 Uncaught TypeError: Cannot read property 'zoom' of undefined

My setup:
https://github.com/filipenevola/easytennis/blob/master/collections/place.coffee#L26

It looks like a bug because even when I ommit 'zoom' config it fails.

**Comment by mpowaga** [comment]
Seems to be solved. Closing. Feel free to open if it still doesn't work.
