### ISSUE TITLE
Pressing enter when using the search box submits the form

### ISSUE THREAD

**Issue by rgoodie** [yogiben/meteor-autoform-map#19]
First off, thank you so much for this slice of code. This may not be a bug report as much as a request for help. 

I've defined this in a Schema as such 
```
 location: {
    label: "Place a marker on your approximate location",
    type: String,
    autoform: {
      type: 'map',
      afFieldInput: {
        searchBox: true,
        autolocate: true,
        geolocation: true,
        defaultLat: 42.056,
        defaultLon: -87.674,
        zoom:15
      }
    }
  },
```
Calling it as such:
`{{> afQuickField name="location" }}`

However, if I try to use the search box (and press Enter), it submits that current form. I've tried to (unsuccessfully) curtail the behavior with this 

```
'click .af-map-search-box ' :  function( event ) {
		event.preventDefault();
	}
```

Is there a better way to mitigate this?

**Comment by mpowaga** [comment]
Fixed with this [commit](https://github.com/yogiben/meteor-autoform-map/commit/dfced11ef6741eb81f95cbed1016c2ae4443ba94).
