### ISSUE TITLE
An option to have [longitute,latitude] as I work with GeoJSON objects

### ISSUE THREAD

**Issue by yvann** [yogiben/meteor-autoform-map#20]
Hello,

Could you add a way to have the coordinates in the opposite order (longitude,latitude) ?

Mainly due of http://docs.mongodb.org/manual/applications/geospatial-indexes/#spherical

Thank you

**Comment by yvann** [comment]
Or maybe a better option to have the whole GeoJSON output of the point object :
```
{
    "type": "Point",
    "coordinates": [102.0, 0.5]
}
```

**Comment by HazemKhaled** [comment]
@yvann Check this pull request #29
