### ISSUE TITLE
Number field type to enable geospatial search 

### ISSUE THREAD

**Issue by hesenp** [yogiben/meteor-autoform-map#24]
Hey there, 

I'm so grateful about this package. Thanks a lot for making and sharing it. 

However, I noticed that the location values are stored as strings in collection. I wonder if there's any specific reason to do so? I would be very happy to have the field stored in {"lng": Number, "lat": Number} in order to enable geospatial search in MongoDB. Wondering if there's any quick workaround? 

I'm trying to understand your code (I'm pretty new to JS), and can submit a pull request if you would give me some code review. Please let me know if this works. Thanks a lot. 

Hesen

**Comment by normanhh3** [comment]
+1 for not killing geospatial search in MongoDB by using strings

**Comment by mpowaga** [comment]
We always return values as a string but seems that autoform converts string to number automatically. I updated readme, here's an example how you can save lat and lng as a number:

```
Schemas.Cities = new SimpleSchema
	location:
		type: Object
		autoform:
			type: 'map'
			afFieldInput:
				# options
	'location.lat':
		type: Number
		decimal: true
	'location.lng':
		type: Number
		decimal: true
```
