### ISSUE TITLE
Issue when using this package along with 

### ISSUE THREAD

**Issue by theroadrunnershow** [yogiben/meteor-autoform-map#25]
Hi , Thanks for this package, it was working wonderfully well till I added dburles:google-maps package. Please check this link for details: 
http://stackoverflow.com/questions/29886354/meteor-autoform-maps-google-maps-package-error

The map in the autoform does not render with TypeError. Could you please provide guidance?

**Comment by elie222** [comment]
See:
https://github.com/yogiben/meteor-autoform-map/issues/9
