### ISSUE TITLE
[enhancement ] Are you planning to add  google autocomplete input field ?

### ISSUE THREAD

**Issue by tinchox5** [yogiben/meteor-autoform-map#33]
Hi, I asked that because I think it would be nice to retrieve some properties of this google autocomplete input field , like in this packcage https://github.com/abdj/autoform-google-places-input/

**Comment by mpowaga** [comment]
Thanks. I think it's good idea. Will give it a shot when I have some more spare time.

**Comment by sakulstra** [comment]
this would be awesome! :+1:
