### ISSUE TITLE
Get current location doesn't work.

### ISSUE THREAD

**Issue by rapito** [yogiben/meteor-autoform-map#42]
When trying to get current Location, the following error appears in the console:

```
Uncaught TypeError: _this.setMarker is not a function
```

**Comment by josephdburdick** [comment]
Can confirm, location button is broken but my error is different:
`Uncaught TypeError: Cannot read property 'zoom' of undefined
    (anonymous function) @ autoform-map.coffee:144`

**Comment by JTL1992** [comment]
+ 1 me too, 

autoform-map.coffee:144    Uncaught TypeError: Cannot read property 'zoom' of undefined

**Comment by zreiby** [comment]
+1

**Comment by aedanmcgarry** [comment]
+1

autoform-map.coffee:144 Uncaught TypeError: Cannot read property 'zoom' of undefined

**Comment by isstaif** [comment]
+1 

`autoform-map.coffee:144 Uncaught TypeError: Cannot read property 'zoom' of undefined`

**Comment by rapito** [comment]
This was merged into master.
