### ISSUE TITLE
Search box isn't appearing

### ISSUE THREAD

**Issue by nicolascarey** [yogiben/meteor-autoform-map#8]
I saw this was a recent addition? I have searchBox set to true in my autoform options but it isn't showing. Any idea?

**Comment by yogiben** [comment]
Any js errors?

There's an implementation of this in my starter repo. You could check that out.

**Comment by nicolascarey** [comment]
Nope no errors.

Map looks like this:
![image](https://cloud.githubusercontent.com/assets/3822873/5596232/dfcaa6c4-9280-11e4-99eb-13ab0c4bffb7.png)
as you can see it does look a little funny on the left where the zoom-in/out normally is.

Will check out the starter repo now.

**Comment by nicolascarey** [comment]
I just tried the starter repo too and it doesnt seem to show a search box either:

![image](https://cloud.githubusercontent.com/assets/3822873/5596322/f1f29d46-9282-11e4-818c-bf237eda4759.png)

**Comment by mpowaga** [comment]
@yogiben This feature was introduced in version 0.0.2 which seems to not be released on atmosphere yet.

**Comment by nicolascarey** [comment]
Ah that would explain it as I installed via atmosphere. @yogiben will that version be released via atmosphere sometime soon?

**Comment by mpowaga** [comment]
@nicolascarey it is now released.

**Comment by yogiben** [comment]
My apologies to both of you for the delay.
