### ISSUE TITLE
Conflicts with dburles:google-maps

### ISSUE THREAD

**Issue by bmx269** [yogiben/meteor-autoform-map#9]
A great package for displaying maps is conflicting with the google maps api used in this package. Is is possible to use https://atmospherejs.com/dburles/google-maps instead?

**Comment by bmx269** [comment]
it is related to

````js
Template.afMap.rendered = function() {
  this.data.options = _.extend({}, defaults, this.data.atts);
  this.data.marker = void 0;
  this.data.setMarker = (function(_this) {
 ...
  })(this);
  return GoogleMaps.init({  <-----------------
    libraries: 'places'
  }, (function(_this) {
    return function() {
    ...
  })(this));
};
````

**Comment by bmx269** [comment]
Looks to be a namespace conflict for "GoogleMaps"

**Comment by mpowaga** [comment]
Try to contact [dburles:google-maps](https://github.com/dburles/meteor-google-maps/) or [mrt:googlemaps](https://github.com/drewjw81/meteor-googlemaps) developers. There's nothing I can do to solve this issue.

**Comment by theroadrunnershow** [comment]
How about using dburles:google-maps instead of mrt:googlemaps? It seems GoogleMaps not exposed correctly as per @dburles

**Comment by nikhildaga** [comment]
@theroadrunnershow :+1: 
@mpowaga : Can we use dburles:google-maps instead of mrt:googlemaps

https://github.com/yogiben/meteor-autoform-map/blob/master/package.js

**Comment by ambbell** [comment]
+1 for using dburles:google-maps instead of mrt:googlemaps
